### ISSUE TITLE
iOS Beta May Use Additional Domain

### ISSUE THREAD

**Issue by Xaositek** [Rogacz/private-relay#1]
I noticed when adding your two lists that some devices on iOS 15.3 beta were calling out to two more domains, and actually not getting blocked from Private Relay, that may need to be added.

I have two devices running iOS 15.3 beta 2 and these are the only two on my network connecting to them.

I would ask you to review:
**canary.mask.apple-dns.net**
**mask-canary.icloud.com**

**Comment by Rogacz** [comment]
Hi
thanks, I don't have any device with iOS beta now, so I will just trust you on this one :)
I've added domains to [pr2.txt](https://github.com/Rogacz/private-relay/blob/main/pr2.txt)
